# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openswarm < Formula
  desc "Multi-agent task orchestration CLI — swarm messaging, tasks, panes, and worktrees"
  homepage "https://github.com/justEstif/openswarm"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justEstif/openswarm/releases/download/v0.1.0/swarm_0.1.0_darwin_amd64.tar.gz"
      sha256 "14d932ef7cf67c8a0922fa7fbf63a3f9911b820bc1278bb4488cacbd5caecff1"

      define_method(:install) do
        bin.install "swarm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justEstif/openswarm/releases/download/v0.1.0/swarm_0.1.0_darwin_arm64.tar.gz"
      sha256 "5b14a770807bc29530650246b2ef0b5b73764afade994825104e56065cb6458f"

      define_method(:install) do
        bin.install "swarm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/justEstif/openswarm/releases/download/v0.1.0/swarm_0.1.0_linux_amd64.tar.gz"
      sha256 "c2650be01389bd1b72663bc991570a2adef75080915c889116956cf138c6ec98"
      define_method(:install) do
        bin.install "swarm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justEstif/openswarm/releases/download/v0.1.0/swarm_0.1.0_linux_arm64.tar.gz"
      sha256 "25f427cfaeba4ed889f74c2f38d3c2430d14e4b12efe6342b56ced461242db09"
      define_method(:install) do
        bin.install "swarm"
      end
    end
  end

  test do
    system "#{bin}/swarm", "--version"
  end
end
