# This file was generated by GoReleaser. DO NOT EDIT.
cask "openswarm" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/justEstif/openswarm/releases/download/v#{version}/swarm_#{version}_darwin_amd64.tar.gz"
      sha256 "86909e3c24a231a49f292183a352122c5483575a9674817755d00117c55521d3"
    end
    on_arm do
      url "https://github.com/justEstif/openswarm/releases/download/v#{version}/swarm_#{version}_darwin_arm64.tar.gz"
      sha256 "097a15a381379c364b8bd88f28ead10a040f4c472af1a52f2726196c6815d044"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/justEstif/openswarm/releases/download/v#{version}/swarm_#{version}_linux_amd64.tar.gz"
      sha256 "ae9df38e30f254c96df1845d34ac85816d0a933fc8b5aad17bca9948ade108d0"
    end
    on_arm do
      url "https://github.com/justEstif/openswarm/releases/download/v#{version}/swarm_#{version}_linux_arm64.tar.gz"
      sha256 "72197cc4bf072346d09c4f5e9fab134093203adea232a568c55b089bf851b277"
    end
  end

  name "openswarm"
  desc "Multi-agent task orchestration CLI — swarm messaging, tasks, panes, and worktrees"
  homepage "https://github.com/justEstif/openswarm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/swarm"]
    end
  end

  # No zap stanza required

end
