# This file was generated by GoReleaser. DO NOT EDIT.
cask "openswarm" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/justEstif/openswarm/releases/download/v#{version}/swarm_#{version}_darwin_amd64.tar.gz"
      sha256 "b6657a1d271d6e33819a696fad55d7abdc120b292beb90f907f9c09e8fe435e2"
    end
    on_arm do
      url "https://github.com/justEstif/openswarm/releases/download/v#{version}/swarm_#{version}_darwin_arm64.tar.gz"
      sha256 "b4f7bd994b365c19581270edb88ef9495ab583d3c951d6ab59b6af70385e33b1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/justEstif/openswarm/releases/download/v#{version}/swarm_#{version}_linux_amd64.tar.gz"
      sha256 "e3c4f61099b3d048ba9fbc8cfc47d65363f57a3fd9565e4eb78b7df327b4e957"
    end
    on_arm do
      url "https://github.com/justEstif/openswarm/releases/download/v#{version}/swarm_#{version}_linux_arm64.tar.gz"
      sha256 "6ae21a08a0a1ee092d908fa71d104b6e38a35f647d7fe1b5e0d9f96ddb40985d"
    end
  end

  name "openswarm"
  desc "Multi-agent task orchestration CLI — swarm messaging, tasks, panes, and worktrees"
  homepage "https://github.com/justEstif/openswarm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/swarm"]
    end
  end

  # No zap stanza required

end
