# This file was generated by GoReleaser. DO NOT EDIT.
cask "qry" do
  version "0.5.6"

  on_macos do
    on_intel do
      url "https://github.com/justEstif/qry/releases/download/v#{version}/qry_#{version}_darwin_amd64.tar.gz"
      sha256 "7d42979037be42580f1d7cf8abb75a7861a0b58c03e0f734599569e1f851c031"
    end
    on_arm do
      url "https://github.com/justEstif/qry/releases/download/v#{version}/qry_#{version}_darwin_arm64.tar.gz"
      sha256 "7c398caccc44d10f270ab2bf68ad2b21548007434e2581c0017c7fc42202834c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/justEstif/qry/releases/download/v#{version}/qry_#{version}_linux_amd64.tar.gz"
      sha256 "940f3e4fc8762bf4b7f1642ba1a67786678090d220183808da63eaf36cea7efc"
    end
    on_arm do
      url "https://github.com/justEstif/qry/releases/download/v#{version}/qry_#{version}_linux_arm64.tar.gz"
      sha256 "c2589d620f633ca80712fac7d7d57137718df193d6fded4f3924027c5e6c2d78"
    end
  end

  name "qry"
  desc "Terminal-native agent-first search CLI that outputs JSON"
  homepage "https://github.com/justestif/qry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qry"]
    end
  end

  # No zap stanza required

end
