# This file was generated by GoReleaser. DO NOT EDIT.
cask "qry" do
  version "0.5.3"

  on_macos do
    on_intel do
      url "https://github.com/justEstif/qry/releases/download/v#{version}/qry_#{version}_darwin_amd64.tar.gz"
      sha256 "237c96269494a35023bd05e3ef1110121dee7d4caba7f1fe8e13d003b6cdff2a"
    end
    on_arm do
      url "https://github.com/justEstif/qry/releases/download/v#{version}/qry_#{version}_darwin_arm64.tar.gz"
      sha256 "d9ecc4bf1c84b9b21924f654545a018ba8d99f318ec38c04d436db7b6008ff1d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/justEstif/qry/releases/download/v#{version}/qry_#{version}_linux_amd64.tar.gz"
      sha256 "f522ea07178311029dd61adb582f4f990ccec942674419480a238db8f8c9942a"
    end
    on_arm do
      url "https://github.com/justEstif/qry/releases/download/v#{version}/qry_#{version}_linux_arm64.tar.gz"
      sha256 "ae6b87226b89871e6ce32febd17c4a7a2f1ea4ebf0ebaad1dbc1a69b9cb6f683"
    end
  end

  name "qry"
  desc "Terminal-native agent-first search CLI that outputs JSON"
  homepage "https://github.com/justestif/qry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qry"]
    end
  end

  # No zap stanza required

end
