# This file was generated by GoReleaser. DO NOT EDIT.
cask "qry" do
  version "0.5.8"

  on_macos do
    on_intel do
      url "https://github.com/justEstif/qry/releases/download/v#{version}/qry_#{version}_darwin_amd64.tar.gz"
      sha256 "50991f342109152b7763c64571f1a697414d5ed0cd9fe28d5834cb73d17ed9d0"
    end
    on_arm do
      url "https://github.com/justEstif/qry/releases/download/v#{version}/qry_#{version}_darwin_arm64.tar.gz"
      sha256 "e2b7060a4ff11a760370db614724214a81d3a7b1636a797057b97407790a7dc8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/justEstif/qry/releases/download/v#{version}/qry_#{version}_linux_amd64.tar.gz"
      sha256 "e4d4f0ea219298ce66d487bbc63e3b0fa7db22bac73775957ab19b55c825bd5b"
    end
    on_arm do
      url "https://github.com/justEstif/qry/releases/download/v#{version}/qry_#{version}_linux_arm64.tar.gz"
      sha256 "623bd66ccb27c742c120ac450e9f69fcdd9fd2b53954d779afb9d52c9321d626"
    end
  end

  name "qry"
  desc "Terminal-native agent-first search CLI that outputs JSON"
  homepage "https://github.com/justestif/qry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qry"]
    end
  end

  # No zap stanza required

end
